#!/usr/bin/env bash
# setup_env.sh — Install all prerequisites for building ssh-serial-bridge
# Target: Ubuntu / Debian (including WSL2)
set -euo pipefail

echo "=== [1/6] Installing system packages ==="
sudo apt update
sudo apt -y install \
    git python3 python3-pip gcc build-essential curl \
    pkg-config libudev-dev libtinfo5 clang libclang-dev \
    llvm-dev udev libssl-dev python3.10-venv

echo "=== [2/6] Installing Rust (rustup) ==="
if command -v rustup &>/dev/null; then
    echo "rustup already installed — skipping."
else
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

# Make cargo/rustup available in this script session
# shellcheck source=/dev/null
source "$HOME/.cargo/env"

echo ""
echo "NOTE: Add the following line to your shell config (~/.bashrc, ~/.zshrc, etc.)"
echo "      if it is not already present:"
echo ""
echo '      source "$HOME/.cargo/env"'
echo ""

echo "=== [3/6] Installing Cargo tools ==="
cargo install ldproxy
cargo install espup
cargo install cargo-espflash

echo "=== [4/6] Installing ESP32-S3 toolchain via espup ==="
espup install
espup update

echo "=== [5/6] Sourcing ESP-IDF environment ==="
# export-esp.sh is generated by espup in the home directory
EXPORT_ESP="$HOME/export-esp.sh"
if [[ -f "$EXPORT_ESP" ]]; then
    # shellcheck source=/dev/null
    source "$EXPORT_ESP"
    echo "Sourced $EXPORT_ESP"
else
    echo "WARNING: $EXPORT_ESP not found. Run '. ~/export-esp.sh' manually."
fi

echo "=== [6/6] Adding udev rules for ESP32 (VID 303a:1001) ==="
sudo sh -c 'echo "SUBSYSTEMS==\"usb\", ATTRS{idVendor}==\"303a\", ATTRS{idProduct}==\"1001\", MODE=\"0666\"" > /etc/udev/rules.d/99-esp32.rules'
sudo udevadm control --reload-rules
sudo udevadm trigger

echo ""
echo "=== Setup complete ==="
echo "Open a new terminal (or run 'source \"\$HOME/.cargo/env\" && source ~/export-esp.sh')"
echo "then proceed with 'bash setup_components.sh' and 'cargo build --release'."
